name: Docker Integration Tests
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration-test:
    runs-on: ubuntu-22.04
    services:
      mosquitto:
        image: eclipse-mosquitto:2.0
        ports:
          - 1883:1883
        volumes:
          - ./tests/mosquitto/config:/mosquitto/config
          - mosquitto-data:/mosquitto/data
          - mosquitto-log:/mosquitto/log
        options: >-
          --health-cmd "mosquitto_sub -t 'test' -u test -P test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Ensure config files exist
        run: |
          mkdir -p tests/mosquitto/config
          touch tests/mosquitto/config/mosquitto.conf tests/mosquitto/config/passwd
          echo "# Allow external connections" > tests/mosquitto/config/mosquitto.conf
          echo "listener 1883" >> tests/mosquitto/config/mosquitto.conf
          echo "allow_anonymous false" >> tests/mosquitto/config/mosquitto.conf
          echo "password_file /mosquitto/config/passwd" >> tests/mosquitto/config/mosquitto.conf
          echo "persistence true" >> tests/mosquitto/config/mosquitto.conf
          echo "persistence_location /mosquitto/data/" >> tests/mosquitto/config/mosquitto.conf
          echo "log_dest file /mosquitto/log/mosquitto.log" >> tests/mosquitto/config/mosquitto.conf
          chmod -R 644 tests/mosquitto/config/*
      - name: Debug config directory
        run: |
          ls -l .
          ls -l *
          ls -l tests/
          ls -l tests/mosquitto/config/
          cat tests/mosquitto/config/mosquitto.conf
          cat tests/mosquitto/config/passwd
      - name: Set up Mosquitto credentials
        run: |
          docker exec $(docker ps -q -f "ancestor=eclipse-mosquitto:2.0") mosquitto_passwd -b /mosquitto/config/passwd test test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        run: |
          docker build -t mqtt-monitor:test -f tests/Dockerfile .
      - name: Run integration tests
        run: |
          docker run --network host -v $(pwd):/app mqtt-monitor:test pytest /app/tests/test_mqtt-monitor.py
