name: Docker Integration Tests
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration-test:
    runs-on: ubuntu-22.04
    services:
      mosquitto:
        image: eclipse-mosquitto:2.0
        ports:
          - 1883:1883
        volumes:
          - ./tests/mosquitto.conf:/mosquitto/config/mosquitto.conf
          - ./tests/passwd:/mosquitto/config/passwd
        options: >-
          --health-cmd "mosquitto_ctrl dynsec getDefaultACL test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Mosquitto credentials
        run: |
          docker exec $(docker ps -q -f "ancestor=eclipse-mosquitto:2.0") mosquitto_passwd -b /mosquitto/config/passwd test test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t mqtt-monitor:test -f tests/Dockerfile .
      - name: Run integration tests
        run: |
          docker run --network host -v $(pwd):/app mqtt-monitor:test pytest /app/tests/test_mqtt-monitor.py
