name: Docker Integration Tests
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build custom Mosquitto image
        run: |
          docker build -t custom-mosquitto:test -f ${{ github.workspace }}/tests/mosquitto/Dockerfile ${{ github.workspace }}/tests/mosquitto
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        run: |
          docker build -t mqtt-monitor:test -f ${{ github.workspace }}/tests/Dockerfile ${{ github.workspace }}
      - name: Run integration tests
        run: |
          docker run --network host -v ${{ github.workspace }}:/app mqtt-monitor:test pytest /app/tests/test_mqtt-monitor.py
    services:
      mosquitto:
        image: custom-mosquitto:test
        ports:
          - 1883:1883
        volumes:
          - mosquitto-data:/mosquitto/data
          - mosquitto-log:/mosquitto/log
        options: >-
          --health-cmd "mosquitto_sub -t 'test' -u test -P test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
