name: Docker Integration Tests
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify passwd file
        run: |
          ls -l ${{ github.workspace }}/tests/mosquitto/config
          cat ${{ github.workspace }}/tests/mosquitto/config/passwd
      - name: Build custom Mosquitto image
        run: |
          docker build -t custom-mosquitto:test -f ${{ github.workspace }}/tests/mosquitto/Dockerfile ${{ github.workspace }}/tests/mosquitto
      - name: Run Mosquitto container
        run: |
          docker run -d --name mosquitto -p 1883:1883 -v mosquitto-data:/mosquitto/data -v mosquitto-log:/mosquitto/log --health-cmd "mosquitto_ctrl dynsec getDefaultACLAccess" --health-interval 10s --health-timeout 5s --health-retries 5 custom-mosquitto:test
      - name: Debug Mosquitto logs
        run: |
          sleep 5
          docker logs mosquitto
      - name: Wait for Mosquitto to be healthy
        run: |
          for i in {1..30}; do
            if docker inspect mosquitto --format='{{.State.Health.Status}}' | grep -q "healthy"; then
              echo "Mosquitto is healthy"
              exit 0
            fi
            echo "Waiting for Mosquitto to be healthy..."
            sleep 2
          done
          echo "Mosquitto failed to become healthy"
          docker logs mosquitto
          exit 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        run: |
          docker build -t mqtt-monitor:test -f ${{ github.workspace }}/tests/Dockerfile ${{ github.workspace }}
      - name: Debug config file
        run: |
          docker run --rm mqtt-monitor:test cat /app/mqtt-monitor.conf
      - name: Run integration tests
        run: |
          docker run --network host -v ${{ github.workspace }}:/app mqtt-monitor:test pytest /app/tests/test_mqtt_monitor.py
      - name: Stop Mosquitto container
        if: always()
        run: |
          docker stop mosquitto || true
          docker rm mosquitto || true
