name: PR Validation
on:
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt pytest pylint
      - name: Run pylint
        run: |
          pylint --rcfile=.pylintrc src/*.py
      - name: Run unit tests
        run: |
          pytest tests/test_mqtt_monitor.py --ignore=tests/test_mqtt_publish_integration
