name: PR Validation
on:
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 src/mqtt-monitor.py
      - name: Run tests
        run: pytest tests/test_mqtt-monitor.py
