name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev debhelper
      - name: Create .deb structure
        run: |
          mkdir -p mqtt-monitor_${{ env.VERSION }}/{DEBIAN,usr/bin,etc/mqtt-monitor,lib/systemd/system}
          cp src/mqtt-monitor.py mqtt-monitor_${{ env.VERSION }}/usr/bin/
          cp src/mqtt-monitor.conf mqtt-monitor_${{ env.VERSION }}/etc/mqtt-monitor/
          cp debian/mqtt-monitor.service mqtt-monitor_${{ env.VERSION }}/lib/systemd/system/
          sed "s/Version: 1.0-1/Version: ${{ env.VERSION }}/" debian/control > mqtt-monitor_${{ env.VERSION }}/DEBIAN/control
          cp debian/postinst mqtt-monitor_${{ env.VERSION }}/DEBIAN/
          cp debian/prerm mqtt-monitor_${{ env.VERSION }}/DEBIAN/
          cp debian/postrm mqtt-monitor_${{ env.VERSION }}/DEBIAN/
          chmod 755 mqtt-monitor_${{ env.VERSION }}/usr/bin/mqtt-monitor.py
          chmod 644 mqtt-monitor_${{ env.VERSION }}/etc/mqtt-monitor/mqtt-monitor.conf
          chmod 644 mqtt-monitor_${{ env.VERSION }}/lib/systemd/system/mqtt-monitor.service
          chmod 755 mqtt-monitor_${{ env.VERSION }}/DEBIAN/{postinst,prerm,postrm}
      - name: Build .deb
        run: dpkg-deb --build mqtt-monitor_${{ env.VERSION }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: mqtt-monitor_${{ env.VERSION }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
